# Importing Libraries

In [1]:
!pip install matplotlib
!pip install tensorflow
!pip install pandas
!pip install seaborn

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Data Preprocessing

### Training Image Preprocessing

In [3]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
#     pad_to_aspect_ratio=False,
#     data_format=None,
#     verbose=True,
)

Found 70295 files belonging to 38 classes.


### Validation Image Preprocessing

In [4]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
#     pad_to_aspect_ratio=False,
#     data_format=None,
#     verbose=True,
)

Found 17572 files belonging to 38 classes.


In [5]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [6]:
for x,y in training_set:
    print(x)
    print(y)
    break

tf.Tensor(
[[[[121.25 100.25 109.25]
   [140.   119.   128.  ]
   [130.   109.   118.  ]
   ...
   [133.5  120.5  130.5 ]
   [143.25 130.25 140.25]
   [150.   137.   147.  ]]

  [[139.25 118.25 127.25]
   [143.   122.   131.  ]
   [130.25 109.25 118.25]
   ...
   [149.5  136.5  146.5 ]
   [166.   153.   163.  ]
   [139.25 126.25 136.25]]

  [[143.25 122.25 131.25]
   [122.25 101.25 110.25]
   [144.   123.   132.  ]
   ...
   [150.25 137.25 147.25]
   [144.5  131.5  141.5 ]
   [159.75 146.75 156.75]]

  ...

  [[169.5  154.5  161.5 ]
   [152.   137.   144.  ]
   [157.   142.   149.  ]
   ...
   [193.75 183.75 192.75]
   [185.25 175.25 184.25]
   [195.25 185.25 194.25]]

  [[167.25 152.25 159.25]
   [164.   149.   156.  ]
   [159.75 144.75 151.75]
   ...
   [192.25 182.25 191.25]
   [189.   179.   188.  ]
   [190.5  180.5  189.5 ]]

  [[168.   153.   160.  ]
   [161.25 146.25 153.25]
   [168.   153.   160.  ]
   ...
   [195.5  185.5  194.5 ]
   [202.   192.   201.  ]
   [199.25 189.25 19

In [7]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[151.25 150.25 156.25]
   [155.5  154.5  160.5 ]
   [150.   149.   155.  ]
   ...
   [143.   138.   145.  ]
   [144.   139.   146.  ]
   [163.   158.   165.  ]]

  [[171.   170.   176.  ]
   [167.5  166.5  172.5 ]
   [161.75 160.75 166.75]
   ...
   [145.75 140.75 147.75]
   [143.5  138.5  145.5 ]
   [152.   147.   154.  ]]

  [[167.5  164.5  171.5 ]
   [182.75 179.75 186.75]
   [173.25 170.25 177.25]
   ...
   [161.   156.   163.  ]
   [156.25 151.25 158.25]
   [150.5  145.5  152.5 ]]

  ...

  [[180.75 175.75 181.75]
   [192.   187.   193.  ]
   [183.25 178.25 184.25]
   ...
   [168.75 163.75 169.75]
   [168.75 163.75 169.75]
   [143.5  138.5  144.5 ]]

  [[184.   179.   185.  ]
   [176.5  171.5  177.5 ]
   [195.75 190.75 196.75]
   ...
   [167.5  162.5  168.5 ]
   [162.75 157.75 163.75]
   [156.75 151.75 157.75]]

  [[188.25 183.25 189.25]
   [187.25 182.25 188.25]
   [193.   188.   194.  ]
   ...
   [146.25 141.25 147.25]
   [162.   157.   163.  ]
   [142.5  137.5  14

### To avoid overshooting
1. Choose small learning rate default 0.001 , we are taking 0.0001
2. There may be chance of underfitting, so increase number of neuron
3. Add more Convolution layer to extract more important feature from images, there may be possibility that model unable to capture relevant feature or model is confusing due to lack of feature so feed with more feature

## Building Model

In [8]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten, Dropout
from tensorflow.keras.models import Sequential

In [9]:
model=Sequential()

## Building Convolutional Layer

In [10]:
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=[128, 128, 3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

C:\Users\gupta\Desktop\plant disease detection\tfenv\lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


In [11]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [12]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [13]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [14]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [15]:
model.add(Dropout(0.25)) #To avoid overfitting

In [16]:
model.add(Flatten())

In [17]:
model.add(Dense(units=1500,activation='relu'))

In [18]:
model.add(Dropout(0.4))

In [19]:
## Output Layer
model.add(Dense(units=38,activation='softmax'))

## Compiling Model

In [20]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [21]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 126, 126, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 63, 63, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 61, 61, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 30, 30, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 28, 28, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 14, 14, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 12, 12, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 6, 6, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 6, 6, 512)           │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 4, 4, 512)           │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 2048)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1500)                │       3,073,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 1500)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 38)                  │          57,038 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

## Model Training

In [ ]:
training_history=model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 3747s 2s/step - accuracy: 0.3985 - loss: 2.1326 - val_accuracy: 0.8401 - val_loss: 0.5147
Epoch 2/10
 114/2197 ━━━━━━━━━━━━━━━━━━━━ 49:35 1s/step - accuracy: 0.8028 - loss: 0.5951

## Model Evaluation

In [ ]:
#Model Evaluation on Training set
train_loss, train_acc = model.evaluate(training_set)
#Training set Accuracy
print('Training accuracy:', train_acc)

In [ ]:
print(train_loss,train_acc)

In [ ]:
#Validation set Accuracy
#val_loss, val_acc = model.evaluate(validation_set)
#print('Validation accuracy:', val_acc)